name: Validate JSON

on: [push, pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.3.1
        with:
          comment: true
          json_schema_version: draft-2020-12
          json_schema: data.schema.json
          files: |
            data.json
